name: Search and Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  search_and_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Search for string and set output if found
      id: search
      run: |
        # Set the file path and the search string
        file_path="main.cs"
        search_string="GetToken();"

        # Check if the search string exists in the file
        if grep -q "$search_string" "$file_path"; then
          echo "The string '$search_string' was found in the file."

          # Set the output variable with the comment message
          greeting="Hello there!"
          comment="{$greeting} The correct token is in use."
          echo "::set-output name=comment::$comment"
        else
          echo "The string '$search_string' was not found in the file."

          # Set the output variable with the comment message
          comment="The test token is in use!"
          echo "::set-output name=comment::$comment"
        fi

    - name: Comment on pull request
      if: ${{ always() }}
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prContext = JSON.parse('${{ toJSON(github) }}');
          const prNumber = prContext.context.payload.pull_request.number;
          const owner = prContext.context.repo.owner;
          const repo = prContext.context.repo.repo;
          const comment = "${{ steps.search.outputs.comment }}";

          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

          octokit.issues.createComment({
            owner: owner,
            repo: repo,
            issue_number: prNumber,
            body: comment
          });
